### ISSUE TITLE
Installation doesn't result in `kiwi.install`

### ISSUE THREAD

**Issue by bobvanderlinden** [jakogut/KiWI#1]
When I execute `python setup.py install` it doesn't create any `kiwi.install` file in my `bin` directory.
I tried this on python 3.5.1 on ArchLinux. Also using `virtualenv` I couldn't get it to work. What exactly should be used to install and run this project?

**Comment by jakogut** [comment]
It won't be in your bin directory, it will be in the site-packages directory of your Python distribution.

'install' is a module that's part of the package. After the package is installed, run `python -m kiwi.install` to start the installer.
